### ISSUE TITLE
Generic use case

### ISSUE THREAD

**Issue by snauth** [andrewcooke/uykfg#1]
Hi!
Got the db to fill with artists, tracks and relations, which looks very good. Now I basically would like to put this to use outside MPD. I played one evening with the code but because my Python-Fu is severely limited I did not get very far. My domestic audio setup is based on liquidsoap feeding an icecast server, so I would need another script (let's say add_similar_track.sh) that takes a track's path as input and returns the path of one or more related songs. I see that the code is built in a way that should make this more generic use case easy, but I just cannot wrap my head around the python logic to make this work. Any help would be highly appreciated.

**Comment by andrewcooke** [comment]
huh.  never heard of liquidsoap before.  looks very interesting.  from a quick scan of the docs i think your best bet is to use an approah as described at http://savonet.sourceforge.net/doc-svn/cookbook.html where it says "Unix interface, dynamic requests".  that seems to call an external program that gives a url.

you also need to pass the current track, but i guess that is fairly easy to do.  so then, yes, i agree you need something like you describe, which would be called.

https://github.com/andrewcooke/uykfg/blob/master/src/uykfg/add.py is quite similar to what you need.  can you modify that?  i can probably spare some time later next week to write what you want, but can't promise anything.

if you do what me to help, it would be useful if you could look at the liquid soap part and get that working to the point where it prints the current track.  then add the output here so it's clear exactly what is given from the liquid soap side.  for example, is it a uri, a file path, a title, or what?

ps if you don't know much about python i am impressed you got this far!

**Comment by snauth** [comment]
I am still experimenting with the endless possibilities of liquidsoap. For instance it can serve metatdata of the current song (like so: http://savonet.sourceforge.net/doc-svn/harbor_http.html), which I already can use (after some ugly sed piping on the command line) to queue new songs within one genre through your bash script uadd. 

I guess what I am looking for here is to make uykfg more generic through a plain text playlist output (instead of the mpd interaction). Ideally the script would take an artist, a genre or a file uri as input and react with a configurable number of file uris, one per line on stdout.

I'll continue to play with this and if you have some time to look into this later I would be most grateful.

**Comment by andrewcooke** [comment]
so the same commands, but sending data to stdout (and reading from stdin)?  playlist format is just a list of file://... urls?

**Comment by snauth** [comment]
Solved it myself (and learned some python). The following new play.py reads from a socket created by liquidsoap the path and filename of the currently playing song and searches then for a related song whose path and and filename is sent to stdout. If nothing is found a random track is returned. The script is called by a dynamic request from liquidsoap. Thanks for your excellent groundwork which made these changes so easy!

``` python
from os.path import split, join
from time import sleep

from sqlalchemy.exc import OperationalError
from sqlalchemy.orm.exc import NoResultFound
from uykfg.music.db.catalogue import Track, Album

from uykfg.music.play import random_track, neighbour_track


import subprocess

try:
    fromsocket = subprocess.check_output("echo request.metadata `echo request.alive | socat /tmp/liq.soc - | perl -ple' exit if $. == 2'` | socat /tmp/liq.soc - | grep filename ", shell=True)
    startfile = fromsocket.rstrip().decode("utf-8")
    startfile = startfile.replace("filename=\"", "")
    startfile = startfile.replace("\"","")
#    print ( startfile )
except:
    pass

def play_links(session, config):
        while True:
                try:
                        if not startfile:
                                queue(config.mp3_path, random_track(session))
                        else:
                                queue(config.mp3_path, neighbour_track(session, find_track(session, config.mp3_path, startfile), config.max_links))
                        break
                except:
                        startfile = ''

def queue(mp3_path, track):
    #path = join(track.album.path, track.file)[len(mp3_path):]
    path = join(mp3_path,track.album.path, track.file)
   # if path.startswith('/'): path = path[1:]
    print (path)

def find_track(session, mp3_path, startfile):
    path, file = split(startfile)
    path = join(mp3_path, path)
    return session.query(Track).join(Album).filter(Album.path == path, Track.file == file).one()
```

**Comment by andrewcooke** [comment]
ah, ok, cool.

**Comment by andrewcooke** [comment]
i had actually already started working on a solution, so i've finished it and pushed it to github.  it may be some use anyway.

it's the new "unext" command.

```
unext u:/some/path/to/file.mp3
```

will give a related track using the same basic idea as play.sh.  but it's more flexible than that.

```
unext 10 a:"Miles %" a:"%Beatles" T:rock
```

will list 10 files from Miles Davis or The Beatles as long as they are not tagged with rock.

**Comment by andrewcooke** [comment]
i should add it's all rather untested and likely to give no results at all if you constraint it too much.

**Comment by snauth** [comment]
Wonderful! Much better than my "solution", thank you!
